from add_deliverable_files_to_package_wdg import AddDeliverableFilesToPackageWdg
from add_files_to_order_wdg import AddFilesToOrderWdg
from add_files_to_task import AddInputFilesToTaskWdg, CreateNewInputFileForTaskWdg
from assign_pipeline_wdg import AssignPipelineWdg
from create_file_for_order_wdg import CreateFileForOrderWdg
from create_instructions_document_from_template_wdg import CreateInstructionsDocumentFromTemplateWdg
from equipment_in_task_wdg import EquipmentInTaskWdg
from instructions_template_builder_wdg import InstructionsTemplateBuilderWdg
from move_input_file_to_output_wdg import MoveInputFileToOutputWdg
from new_pipeline_request_wdg import NewPipelineRequestWdg
from task_inspect_wdg import TaskInspectWdg
