from add_deliverable_files_to_package_wdg import AddDeliverableFilesToPackageWdg
from add_files_to_order_wdg import AddFilesToOrderWdg
from add_files_to_task import AddInputFilesToTaskWdg, CreateNewInputFileForTaskWdg
from add_instructions_from_template_wdg import AddInstructionsFromTemplateWdg
from assign_pipeline_wdg import AssignPipelineWdg
from change_component_for_file_flow_wdg import ChangeComponentForFileFlowWdg
from change_estimated_hours_for_task_wdg import ChangeEstimatedHoursForTaskWdg
from change_order_expected_completion_date import ChangeOrderExpectedCompletionDate
from change_package_instructions_wdg import ChangePackageInstructionsWdg
from change_status_wdg import ChangeStatusWdg, ChangeMultipleFileStatusesOnPackageWdg
from create_file_for_order_wdg import CreateFileForOrderWdg
from create_instructions_document_from_template_wdg import CreateInstructionsDocumentFromTemplateWdg
from delivery_task_inspect_wdg import DeliveryTaskInspectWdg
from department_request_wdg import DepartmentRequestWdg
from edit_file_wdg import EditFileWdg
from edit_instructions_wdg import EditInstructionsWdg
from equipment_in_task_wdg import EquipmentInTaskWdg
from generic_task_inspect_wdg import GenericTaskInspectWdg
from insert_component_in_order_wdg import InsertComponentInOrderWdg, InsertComponentByLanguageWdg,\
    InsertComponentBySeasonWdg
from instructions_builder_load_page import InstructionsBuilderLoadPageWdg
from instructions_template_builder_wdg import InstructionsTemplateBuilderWdg
from link_components_to_packages_wdg import LinkComponentsToPackagesWdg
from move_input_file_to_output_wdg import MoveInputFileToOutputWdg
from new_download_request_wdg import NewDownloadRequestWdg
from new_pipeline_request_wdg import NewPipelineRequestWdg
from package_inspect_wdg import PackageInspectWdg
from task_inspect_wdg import TaskInspectWdg
