from add_task_to_title_order_wdg import AddTaskToTitleOrderWdg
from change_due_date_wdg import ChangeDueDateWdg
from component_instructions_wdg import ComponentInstructionsWdg
from external_rejection_on_title_order_wdg import ExternalRejectionOnTitleOrderWdg
from insert_component_in_package_wdg import InsertComponentByLanguageWdg, InsertComponentInPackageWdg
from insert_package_in_order_wdg import InsertPackageInOrderWdg
from instructions_wdg import InstructionsWdg
from new_order_entry import NewOrderEntryWdg
from order_builder import OrderBuilderWdg
from order_builder_launcher_wdg import OrderBuilderLauncherWdg
from reassign_component_to_package_wdg import ReassignComponentToPackage
from task_instructions_wdg import TaskInstructionsWdg
