from change_due_date_wdg import ChangeDueDateWdg
from change_instructions_wdg import ChangeInstructionsWdg
from change_title_wdg import ChangeTitleWdg
from component_instructions_wdg import ComponentInstructionsWdg
from external_rejection_on_title_order_wdg import ExternalRejectionOnTitleOrderWdg
from insert_component_in_package_wdg import InsertComponentByLanguageWdg, InsertComponentInOrderWdg
from insert_package_in_order_wdg import InsertPackageInOrderWdg, InsertPackageByPlatformWdg
from insert_task_wdg import InsertTaskWdg
from instructions_wdg import InstructionsWdg
from new_order_entry import NewOrderEntryWdg
from order_builder import OrderBuilderWdg
from reassign_component_to_package_wdg import ReassignComponentToPackage
from task_instructions_wdg import TaskInstructionsWdg
